# Generated by Django 3.1.7 on 2021-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('transfer_date', models.DateTimeField()),
            ],
        ),
    ]
